version: "3.7"

services:
  php:
    image: ghcr.io/blumilksoftware/php:8.1
    container_name: escooters
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
